// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyFH0a28AOrjxWAa_jdVG6fb0HPHSlN8I',
    appId: '1:308811835817:web:b1f0488996ada16b487cb8',
    messagingSenderId: '308811835817',
    projectId: 'library-25f22',
    authDomain: 'library-25f22.firebaseapp.com',
    storageBucket: 'library-25f22.appspot.com',
    measurementId: 'G-M3WK3RQXYM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAB0JYBENHWT8DDOPxHk4KyxpvfbEMAP2Q',
    appId: '1:308811835817:android:eb3829fd241852ab487cb8',
    messagingSenderId: '308811835817',
    projectId: 'library-25f22',
    storageBucket: 'library-25f22.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7FXrEQtHLZJlES3LToIonPSNRKbqFRu4',
    appId: '1:308811835817:ios:d3560d87b13c8cdb487cb8',
    messagingSenderId: '308811835817',
    projectId: 'library-25f22',
    storageBucket: 'library-25f22.appspot.com',
    iosBundleId: 'com.example.firstProject',
  );
}
